### PR TITLE
FIX - host update returns 404

### PR DESCRIPTION
**Pull request by joongimin**
# Reason
- Existence of host should not be asserted when updating existing host

### CODE REVIEW

**Comment by frdmn** [comment]
Hi Joon,

thank you for this PR.

Can you elaborate why we should get rid of this check? In my opinion we should check in both situations since both could already contain the newly added hostname, or am I missing something?

Greetings,
Jonas

**Comment by joongimin** [comment]
Hi Jonas,

When you're adding a new host it makes sense to check if the same host already exists. However when you're updating an existing host, in such case as '/api/edit/:host', checking for existing host will always return true and thus causing a 404 error.

Try updating ip of an existing host, without changing its hostname, and you will be able to reproduce the error.

Best,
Joon.

**Comment by frdmn** [comment]
@joongimin You are totally right – I didn't notice this.

**Comment by frdmn** [comment]
Thanks again

:+1:

**Comment by joongimin** [comment]
@frdmn no problem. Thank you for maintaining hostkeeper. :)

**Comment by frdmn** [comment]
No worries, ist actually one of my first projects I am really proud of. 

Let me know in case of feature requests/ideas/improvements.

Also, I'll release your fix with the very next minor release update. :)

Von meinem iPhone gesendet

**Pull request merged**
